# Generated by Django 5.2.1 on 2025-06-14 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaqueteViaje',
            fields=[
                ('id_paquete', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Descripción detallada del paquete.', max_length=255)),
                ('precio', models.IntegerField(help_text='Precio del paquete, sin decimales.')),
                ('destino', models.CharField(help_text='Destino principal del paquete.', max_length=100)),
                ('vuelo', models.CharField(blank=True, help_text='Información del vuelo.', max_length=100, null=True)),
                ('alojamiento', models.CharField(blank=True, help_text='Información del alojamiento.', max_length=100, null=True)),
                ('tour', models.CharField(blank=True, help_text='Información sobre tours incluidos.', max_length=100, null=True)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del paquete (YYYY-MM-DD).')),
                ('fecha_termino', models.DateField(help_text='Fecha de término del paquete (YYYY-MM-DD).')),
            ],
            options={
                'verbose_name': 'Paquete de Viaje',
                'verbose_name_plural': 'Paquetes de Viaje',
                'db_table': 'AGENCIADEVIAJES',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='RUT del cliente, normalizado (ej: 12345678-9).', max_length=12, unique=True)),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono del cliente.', max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'CLIENTE',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField(help_text='Fecha en que se realizó la reserva.')),
                ('estado', models.CharField(help_text='Estado actual de la reserva (Ej: Reservado, Pagado, Cancelada).', max_length=20)),
                ('id_paquete', models.ForeignKey(db_column='id_paquete', help_text='ID del paquete reservado.', on_delete=django.db.models.deletion.CASCADE, to='agencia.paqueteviaje')),
                ('rut_cliente', models.ForeignKey(db_column='rut', help_text='RUT del cliente que hizo la reserva.', on_delete=django.db.models.deletion.CASCADE, to='agencia.cliente', to_field='rut')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'RESERVA',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.BigAutoField(primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(help_text='Método utilizado para el pago (Ej: Débito, Crédito).', max_length=50)),
                ('id_reserva', models.ForeignKey(db_column='id_reserva', help_text='ID de la reserva asociada a este pago.', on_delete=django.db.models.deletion.CASCADE, to='agencia.reserva')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'PAGO',
            },
        ),
    ]
