# Generated by Django 5.2.1 on 2025-06-14 21:27

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(default=10000000000, help_text='Número de teléfono internacional.', max_length=128, region=None, unique=True),
            preserve_default=False,
        ),
    ]
