# Generated by Django 5.2.1 on 2025-06-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0002_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='paqueteviaje',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='paquetes/', verbose_name='Imagen del Paquete'),
        ),
    ]
