# Generated by Django 5.2.1 on 2025-06-15 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0003_paqueteviaje_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paqueteviaje',
            name='imagen',
        ),
        migrations.CreateModel(
            name='ImagenPaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='paquetes_galeria/')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='agencia.paqueteviaje')),
            ],
        ),
    ]
